In [22]:
import numpy as np

In [23]:
array_1d = np.array([1,2,3,4,5,6])
array_1d

array([1, 2, 3, 4, 5, 6])

In [24]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_3d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
array_1d.shape
array_3d.dtype

dtype('int64')

In [28]:
reshaped_array = array_1d.reshape(6,1)
reshaped_array

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
flattened_array = array_2d.flatten()
print(flattened_array)

[1 2 3 4 5 6 7 8 9]


In [32]:
anto =  array_3d.flatten()
print(anto)

[1 2 3 4 5 6 7 8]


In [36]:
a = np.array([1,2,3])
b = np.array([[10,11,12], [13,14,15], [16,17,18]])
dotp = np.dot(a,b)
print(dotp)

[84 90 96]


In [37]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
d_transpose = np.dot(matrix.T, matrix)
print(d_transpose)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
